# Generated by Django 5.0.6 on 2025-09-12 02:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("ambientes", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="GAM",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("user_id_gam_admin", models.CharField(max_length=100)),
                ("user_id_gam_connection", models.CharField(max_length=100)),
                ("ambientes", models.ManyToManyField(to="ambientes.ambiente")),
            ],
        ),
    ]
