# Generated by Django 5.0.6 on 2025-09-12 02:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Projeto",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("version", models.CharField(max_length=20)),
                ("server_kb_alias", models.CharField(max_length=100)),
                ("kb_version", models.CharField(max_length=50)),
                ("target_path", models.CharField(max_length=100)),
                (
                    "arquivos_complementares",
                    models.CharField(blank=True, max_length=100),
                ),
                ("exclude_files", models.CharField(blank=True, max_length=200)),
                (
                    "directory_config_msbuild",
                    models.CharField(blank=True, max_length=200),
                ),
                ("base_gam", models.BooleanField(default=False)),
                ("https", models.BooleanField(default=False)),
            ],
        ),
    ]
