# Generated by Django 5.0.6 on 2025-09-12 02:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("ambientes", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="BancoDeDados",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("service_name", models.CharField(blank=True, max_length=100)),
                ("engine", models.CharField(max_length=50)),
                ("ambientes", models.ManyToManyField(to="ambientes.ambiente")),
            ],
        ),
        migrations.CreateModel(
            name="BancoDados",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("user_id_jenkis", models.CharField(max_length=100)),
                (
                    "banco_de_dados",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="bancos",
                        to="bancodedados.bancodedados",
                    ),
                ),
            ],
        ),
    ]
