# Generated by Django 5.0.6 on 2025-09-12 02:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Genexus",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("gx_server_url", models.CharField(max_length=200)),
                ("gx_server_version", models.CharField(max_length=20)),
                ("gx_server_working_directory", models.CharField(max_length=200)),
                ("gx_server_working_directory_kb", models.CharField(max_length=200)),
            ],
        ),
    ]
